#!/bin/bash

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <seconds> <message>"
  exit 1
fi

total_seconds=$1
message=$2

echo "Waiting for $total_seconds seconds..."
sleep $total_seconds

for i in {1..10}   # you can also use {0..9}
do
  echo "Time's up! $message"
  say "Time's up! $message"
  sleep 30
done
